# Imagen base
FROM node:15-alpine3.13 as base

ENV NODE_ENV=production
EXPOSE 3000
ENV PORT 3000

WORKDIR /app
COPY package*.json ./

RUN npm config list
RUN  npm ci \
    && npm cache clean --force
RUN npm i -g serve

CMD ["npm", "start"]

# Imagen desarrollo
FROM base as dev
ENV NODE_ENV=development
ENV PATH=/app/node_modules/.bin:$PATH
RUN npm install --only=development
CMD ["npm", "start"]


# Imagen productiva
FROM base as prod
EXPOSE 8080
ENV PORT 8080
COPY . .
RUN npm run build
CMD ["serve", "serve -s build -l 8080"]
