# Imagen base
FROM node:15-alpine3.13 as base

ENV NODE_ENV=production
EXPOSE 5000
ENV PORT 5000

WORKDIR /app
COPY package*.json ./

RUN npm config list
RUN  npm ci \
    && npm cache clean --force

# Imagen desarrollo
FROM base as dev
ENV NODE_ENV=development
ENV PATH=/app/node_modules/.bin:$PATH
RUN npm install --only=development
CMD ["npm", "run", "dev"]


# Imagen productiva
FROM base as prod
COPY . .
CMD ["npm", "start"]
